import type { StoreItem } from "@/types/plugin-store";

export const STORE_ITEMS: StoreItem[] = [
  {
    id: "journal",
    name: "Journal",
    description: "Encrypted journaling with native-feel UI, markdown support, and daily prompts.",
    icon: "📓",
    version: "1.0.0",
    category: "productivity",
    rating: 4.8,
    downloads: 1240,
    author: "Aether",
    permissions: ["db:read", "db:write"],
    installed: true,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "todo",
    name: "Todo List",
    description: "Task management with priorities, due dates, and Activity Bar integration.",
    icon: "✅",
    version: "1.0.0",
    category: "productivity",
    rating: 4.6,
    downloads: 980,
    author: "Aether",
    permissions: ["db:read", "db:write"],
    installed: true,
    updateAvailable: true,
    changelog: "Added recurring tasks and filter presets.",
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "goals",
    name: "Goals",
    description: "Track long-term goals with milestones and cross-plugin progress sharing.",
    icon: "🎯",
    version: "1.0.0",
    category: "productivity",
    rating: 4.5,
    downloads: 760,
    author: "Aether",
    permissions: ["db:read", "db:write"],
    installed: true,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "calendar-sync",
    name: "Calendar Sync",
    description: "Sync tasks and journal entries with external calendar providers.",
    icon: "📅",
    version: "0.9.2",
    category: "integration",
    rating: 4.2,
    downloads: 340,
    author: "Aether",
    permissions: ["network:outbound"],
    installed: false,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "secure-notes",
    name: "Secure Notes",
    description: "Password-protected notes with biometric lock and encrypted storage.",
    icon: "🔒",
    version: "1.2.0",
    category: "security",
    rating: 4.7,
    downloads: 520,
    author: "Aether",
    permissions: ["biometric:read", "db:read", "db:write"],
    installed: false,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "dev-snippets",
    name: "Dev Snippets",
    description: "Save and organize code snippets with syntax highlighting and search.",
    icon: "💻",
    version: "0.8.1",
    category: "developer-tools",
    rating: 4.4,
    downloads: 290,
    author: "Aether",
    permissions: ["db:read", "db:write"],
    installed: false,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "focus-timer",
    name: "Focus Timer",
    description: "Pomodoro-style focus sessions with task integration and break reminders.",
    icon: "⏱️",
    version: "1.1.0",
    category: "productivity",
    rating: 4.3,
    downloads: 410,
    author: "Aether",
    permissions: ["notification:send"],
    installed: false,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "api-inspector",
    name: "API Inspector",
    description: "Debug and inspect secure IPC traffic between plugins.",
    icon: "🔍",
    version: "0.5.0",
    category: "developer-tools",
    rating: 4.0,
    downloads: 180,
    author: "Aether",
    permissions: ["ipc:inspect"],
    installed: false,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "backup-tool",
    name: "Backup Tool",
    description: "Encrypted backups to local disk or cloud storage with scheduling.",
    icon: "💾",
    version: "1.0.1",
    category: "security",
    rating: 4.6,
    downloads: 390,
    author: "Aether",
    permissions: ["fs:read", "fs:write", "network:outbound"],
    installed: false,
    updateAvailable: true,
    changelog: "Added cloud provider support.",
    downloadUrl: "",
    checksum: "",
  },
  {
    id: "webhook-relay",
    name: "Webhook Relay",
    description: "Forward plugin events to external webhooks with retry and auth.",
    icon: "🔗",
    version: "0.7.0",
    category: "integration",
    rating: 3.9,
    downloads: 150,
    author: "Aether",
    permissions: ["network:outbound"],
    installed: false,
    updateAvailable: false,
    downloadUrl: "",
    checksum: "",
  },
];
